### ISSUE TITLE
/renamemap not working properly

### ISSUE THREAD

**Issue by ZUNII** [drunkdriversclub/ddc#5]
**Describe the bug**
So if I try to rename a map for example [DM]Skraxx - "MIND" Control -> Mind Control it applies for moment but if I try to set Mind Control later it doesn't work so I use /nm Mind and it sets the old name again

**To Reproduce**
1. Rename a map
2. *Server Restart*
3. Set the map with the new name

**Expected behavior**
Map should have the new name

**Comment by ce2kettu** [comment]
Hey, thank you for reporting.
I would suspect this is due to all maps being zipped and thus MTA is unable to modify the map's associated meta file. "Why was it working before?" you may ask. That's because none of the maps on Maptest were zipped back then. If we wanted to make this work, it would require a lot of changes. I'd suggest we handle the renaming manually - and that'd up to maptesters themselves. Or, alternatively, we could make a cron task to zip all of the unzipped directories in every map folder except Maptest. This way when maptesters move maps from Maptest they'd automatically zipped within the day.

**Comment by ce2kettu** [comment]
This command has now been removed since it's not working as expected. Read the above comment for the reasoning. Feel free to propose a replacement or anything of that sort.
